In [2]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])
print(arr[1,1,-3])

6
10


In [2]:
#disp
import numpy as np
import random

In [6]:
import random
from tabulate import tabulate
import numpy as np
arr=np.array([random.randint(1,100) for i in range(30)])
print(arr)
a=arr.reshape(6,5)
b=arr.reshape(5,6)
print(a)
print(b)
print(tabulate(a,tablefmt="fancy_grid"))


[68 40 28 32 15 45 73 80 70 48 63 48 46 94  8 89 73 92 37 66 70 13 18 76
 85 40 80 56 39 63]
[[68 40 28 32 15]
 [45 73 80 70 48]
 [63 48 46 94  8]
 [89 73 92 37 66]
 [70 13 18 76 85]
 [40 80 56 39 63]]
[[68 40 28 32 15 45]
 [73 80 70 48 63 48]
 [46 94  8 89 73 92]
 [37 66 70 13 18 76]
 [85 40 80 56 39 63]]
╒════╤════╤════╤════╤════╕
│ 68 │ 40 │ 28 │ 32 │ 15 │
├────┼────┼────┼────┼────┤
│ 45 │ 73 │ 80 │ 70 │ 48 │
├────┼────┼────┼────┼────┤
│ 63 │ 48 │ 46 │ 94 │  8 │
├────┼────┼────┼────┼────┤
│ 89 │ 73 │ 92 │ 37 │ 66 │
├────┼────┼────┼────┼────┤
│ 70 │ 13 │ 18 │ 76 │ 85 │
├────┼────┼────┼────┼────┤
│ 40 │ 80 │ 56 │ 39 │ 63 │
╘════╧════╧════╧════╧════╛


In [4]:
arr=np.array([i for i in range(1,10) if i%2!=0])
print(arr)
print(arr*2)

[1 3 5 7 9]
[ 2  6 10 14 18]


In [8]:
import random
arr=np.array([random.randint(1,1000) for i in range(10)])



In [12]:
arr[arr%2==0]

array([120, 272, 122,  42])

In [7]:
arr[arr%2!=0]
print(arr.max())
print(arr.min())

94
8


In [14]:
a=np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [15]:
a=np.linspace(1,5,10)
a

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [21]:
import numpy as np
a=np.array('[1, 2; 3, 4 ]')
b = a.getI()
print(b)

AttributeError: 'numpy.ndarray' object has no attribute 'getI'

In [30]:
a=np.zeros((5,5),dtype='int8')
a[0:1,:]=1
a[0:5,0:1]=1
a[4:5,:]=1
a[0:5,4:5]=1
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [25]:
a=np.eye(5,k=1)
a=np.eye(5,k=2)
a

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
import numpy as geek  
            
mat = geek.matrix('[3, 4; 5, 6]')  
            
# applying matrix.getI() method  
gfg = mat.getI()  
      
print(gfg) 

[[-3.   2. ]
 [ 2.5 -1.5]]


In [39]:
a=np.zeros((8,8))
a[::2,::2]=1
a[1::2,1::2]=1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [38]:
a=np.array([1,2,3,4,5],dtype='int')
print(a.sum())

15


In [59]:
a=np.array([random.randint(1,100) for i in range(10)])
b=np.array([random.randint(1,100) for i in range(10)])
print(a," ",b)
print(np.intersect1d(a,b))

[52 76 59 59 22 47 91 58 41 94]   [65 95 11 49 74 88 13 36 83 52]
[52]


In [7]:
import numpy as np
a=np.eye(3,k=1)
a

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [62]:
a=np.array([random.randint(1,7) for i in range(20)])
print(a)
print(np.unique(a))

[4 4 3 1 2 7 5 3 7 4 4 2 6 5 4 7 5 7 1 3]
[1 2 3 4 5 6 7]


In [77]:
a=np.array([[random.randint(1,100) for i in range(5)] for j in range(5)])
a[::2,:].sort()
a[1::2,:].sort()
a

array([[31, 44, 67, 72, 86],
       [31, 47, 62, 77, 81],
       [17, 18, 67, 71, 73],
       [41, 47, 55, 57, 96],
       [16, 22, 46, 58, 93]])

In [10]:
#user defined data sort
import numpy as np
a=np.array([[1,'Saptarshi',80],[2,'Afridi',78],[3,'Bishal',85]])
name = a[a[:, 1].argsort()]
marks=a[a[:,2].argsort()]
print(name)
print(marks)

[['2' 'Afridi' '78']
 ['3' 'Bishal' '85']
 ['1' 'Saptarshi' '80']]
[['2' 'Afridi' '78']
 ['1' 'Saptarshi' '80']
 ['3' 'Bishal' '85']]


In [18]:
#user defined data sort
import numpy as np
dt=[('Name','S15'),('Roll','int'),('Marks','int')]
student=[('Amit',5,50),('Bishal',3,87),('Abhishak',10,33)]
x=np.array(student,dtype=dt)
print(x)
print(np.sort(x,order='Roll'))

[(b'Amit',  5, 50) (b'Bishal',  3, 87) (b'Abhishak', 10, 33)]
[(b'Bishal',  3, 87) (b'Amit',  5, 50) (b'Abhishak', 10, 33)]


In [32]:
#mean by each row and column
import random
a=np.array([[random.randint(1,100) for i in range(5)]for i in range(5)])
print(a)
#row
print(np.mean(a[0:1,:]))
print(np.mean(a[1:2,:]))
#column
print(np.mean(a[:,0:1]))
print(np.mean(a[:,1:2]))


print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

[[53 38 94 92 70]
 [99 30 16 37 73]
 [50 89 34 38 62]
 [59 16 16 64 78]
 [78 46 37 57 12]]
69.4
51.0
67.8
43.8
[67.8 43.8 39.4 57.6 59. ]
[69.4 51.  54.6 46.6 46. ]


In [38]:
#finding 2nd largest number in each row and column
print(a)
# print(np.partition(a, -2, axis=0)[:, -2])
# print(np.partition(a, -2, axis=1)[:, -2])
# print(np.partition(a, -2, axis=1)[:, -3])
np.sort(a,axis=0)
print(a)

[[53 38 94 92 70]
 [99 30 16 37 73]
 [50 89 34 38 62]
 [59 16 16 64 78]
 [78 46 37 57 12]]
[[53 38 94 92 70]
 [99 30 16 37 73]
 [50 89 34 38 62]
 [59 16 16 64 78]
 [78 46 37 57 12]]


In [58]:
a=np.array([[random.randint (1,15) for i in range(3)] for i in range(2)])
b=np.array([[random.randint (1,15) for i in range(3)] for i in range(2)])
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[[ 4 15 12  1  2 11]
 [14  8  9  5 14  6]]
[[ 4 15 12]
 [14  8  9]
 [ 1  2 11]
 [ 5 14  6]]


In [51]:
#convert into farenhite
from tabulate import tabulate
a=np.array([random.randint(-50,50) for i in range(7)])
farenhite = lambda x: 5*(x-32)/9
print(a)
print(farenhite(a))
l=[]
l.append(a)
l.append(farenhite(a))
print(tabulate(l,tablefmt='fancy_grid'))

[-18 -17  43  43 -35 -17 -32]
[-27.77777778 -27.22222222   6.11111111   6.11111111 -37.22222222
 -27.22222222 -35.55555556]
╒══════════╤══════════╤══════════╤══════════╤══════════╤══════════╤══════════╕
│ -18      │ -17      │ 43       │ 43       │ -35      │ -17      │ -32      │
├──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ -27.7778 │ -27.2222 │  6.11111 │  6.11111 │ -37.2222 │ -27.2222 │ -35.5556 │
╘══════════╧══════════╧══════════╧══════════╧══════════╧══════════╧══════════╛


In [15]:
#display all the date for the month of 2023
#get the date of yesterday today and tomorrow
#count no of days of a specific month 
import numpy as np
d=np.arange('2023-12-01','2024-01-01',dtype='datetime64[D]')
print(d)
today_date=np.datetime64('today','D')
yestarday=np.datetime64('today','D')-np.timedelta64(1,'D')
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print(yestarday)
print(today_date)
print(tomorrow)
days=np.datetime64('2023-01-01')-np.datetime
print(days)
print(s)

['2023-12-01' '2023-12-02' '2023-12-03' '2023-12-04' '2023-12-05'
 '2023-12-06' '2023-12-07' '2023-12-08' '2023-12-09' '2023-12-10'
 '2023-12-11' '2023-12-12' '2023-12-13' '2023-12-14' '2023-12-15'
 '2023-12-16' '2023-12-17' '2023-12-18' '2023-12-19' '2023-12-20'
 '2023-12-21' '2023-12-22' '2023-12-23' '2023-12-24' '2023-12-25'
 '2023-12-26' '2023-12-27' '2023-12-28' '2023-12-29' '2023-12-30'
 '2023-12-31']
2023-12-06
2023-12-07
2023-12-08


AttributeError: module 'numpy' has no attribute 'count'